site_name: Limber Timber
site_url: https://Wopple.github.io/limber-timber/
repo_url: https://github.com/Wopple/limber-timber
theme:
  name: material
  palette:
    scheme: slate
  features:
  - navigation.instant
  - navigation.sections
  - content.code.copy
extra_css:
- styles/reference.css
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          members: true
          members_order: source
          separate_signature: false
          show_bases: true
          show_labels: false
          show_object_full_path: false
          show_root_full_path: false
          show_root_heading: true
          show_signature_annotations: true
          show_source: false
nav:
- Home: index.md
- Learn: learn.md
- How Tos: how_tos.md
- Reference: reference.md
